# This file is for Streamlit Cloud deployment
# The values are set in the Streamlit dashboard, not here.
GEMINI_API_KEY = "AIzaSyBEXgwJVERXV1aP8OxEeQk2i0b_Ko-t7N8" 
DB_CONNECTION_STRING = "postgresql://neondb_owner:npg_3OTsNjkSol7c@ep-young-fog-af6c3048-pooler.c-2.us-west-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require"